name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # ou a versão do Java que você está usando

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Deploy
        run: |
          echo "Deploying application..."
          # Adicione aqui o comando de deploy se necessário
