name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Este job depende do job de build
    if: github.ref == 'refs/heads/main'  # Apenas executa na branch main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
          echo "Deploying to the server..."

      - name: Notify Deployment Success
        run: echo "Deployment to server was successful!"